# Generated by Django 3.1.1 on 2020-10-02 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('owner', models.CharField(max_length=100)),
                ('passcode', models.CharField(blank=True, max_length=10)),
                ('address', models.CharField(max_length=160)),
                ('created', models.DateTimeField(verbose_name='created at')),
            ],
        ),
        migrations.CreateModel(
            name='UserRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=40)),
                ('role', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PackageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('logistics', models.CharField(max_length=50)),
                ('tracking', models.CharField(max_length=20)),
                ('weight', models.IntegerField(blank=True, default=0)),
                ('volume', models.CharField(blank=True, max_length=20)),
                ('item_info', models.CharField(blank=True, max_length=200)),
                ('comment', models.CharField(blank=True, max_length=400)),
                ('oid', models.CharField(blank=True, max_length=30)),
                ('last_update', models.DateTimeField(verbose_name='last update')),
                ('status', models.CharField(default='0', max_length=20)),
                ('image', models.CharField(blank=True, max_length=60)),
                ('mail_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.mailgroup')),
            ],
        ),
    ]
