# Generated by Django 3.1.1 on 2020-10-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailgroup',
            name='address',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='mailgroup',
            name='owner',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
